services:
  nginx: 
    image: nginx:alpine
    volumes:
      - ./www:/var/www:ro
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./www:/var/www
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://158.160.43.195:80 | grep -c works > /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 5    
